on:
  pull_request:
    types: [opened, reopened]
name: Pull Request
permissions:
  contents: read
  pull-requests: write
jobs:
  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to PR
        uses: technote-space/assign-author@v1